pipeline:
  name: terraform pipepline
  identifier: terraform_pipepline
  projectIdentifier: github
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Dev Environment
        identifier: Deploy_Dev_Environment
        description: ""
        type: Custom
        spec:
          environment:
            environmentRef: dev
            deployToAll: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: ./harness_ci.sh dev
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
