name: Build and Trigger CD

on: push
jobs:
  build_and_trigger:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [dev, qa, stage]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - name: Cache Terraform and AWS CLI
        uses: actions/cache@v3
        with:
          path: ~/.terraform/
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.3.4
      - name: Set up AWS CLI
        uses: aws-actions/aws-cli@v2.4.4
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1.8.4
      - name: Authenticate with Harness
        run: harness login --token ${{ secrets.HARNESS_API_KEY }}
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out
        outputs:
          result: ${{ steps.plan.outputs.result }}
      - name: Review Terraform Plan
        uses: actions/github-script@v4
        with:
          script: |
            cat plan.out
      - name: Terraform Apply (if approved)
        if: ${{ steps.plan.outputs.result == 'approved' }}
        run: terraform apply plan.out
      - name: Trigger Harness CD Pipeline
        uses: harnessio/harness-ci-trigger@v1.1.4
        with:
          app: my-app
          env: ${{ matrix.branch }}
          pipeline: Deploy to Multiple Environments
      - name: Send Notifications
        if: failure()
        uses: …
        with:
          status: ${{ job.status }}
