name: Harness CI/CD and Terraform Apply

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HARNESS_ACCOUNT_ID: ${{ secrets.HARNESS_ACCOUNT_ID }}
      HARNESS_API_KEY: ${{ secrets.HARNESS_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.5  # Adjust the Terraform version as needed

    - name: Set up Harness CLI
      run: |
        curl -O https://downloads.harness.io/cli/production/harness-cli-darwin-amd64.tar.gz
        tar -zxvf harness-cli-darwin-amd64.tar.gz
        mv harness /usr/local/bin/

    - name: Authenticate with Harness
      run: harness auth --account-id $HARNESS_ACCOUNT_ID --api-key $HARNESS_API_KEY

    - name: Trigger Dev Environment in Harness
      run: harness delegate start --daemon
      env:
        DELEGATE_PROFILE: "dev"

    - name: Terraform Init and Apply (Dev)
      run: |
        cd terraform/dev  # Path to your dev Terraform directory
        terraform init
        terraform apply -auto-approve

    - name: Trigger QA Environment in Harness
      run: harness delegate start --daemon
      env:
        DELEGATE_PROFILE: "qa"

    - name: Terraform Init and Apply (QA)
      run: |
        cd terraform/qa  # Path to your QA Terraform directory
        terraform init
        terraform apply -auto-approve

    - name: Trigger Stage Environment in Harness
      run: harness delegate start --daemon
      env:
        DELEGATE_PROFILE: "stage"

    - name: Terraform Init and Apply (Stage)
      run: |
        cd terraform/stage  # Path to your stage Terraform directory
        terraform init
        terraform apply -auto-approve
